# Generated by Django 3.0.3 on 2020-02-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('anonymous', models.BooleanField()),
                ('reported', models.BooleanField(default=False)),
                ('cleanliness', models.IntegerField()),
                ('social_life', models.IntegerField()),
                ('noise', models.IntegerField()),
                ('facilities', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.ImageField(upload_to='review-uploads/')),
                ('photo_desc', models.TextField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Review')),
            ],
        ),
    ]
