# Generated by Django 3.0.2 on 2020-03-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20200305_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
