# Generated by Django 3.0.3 on 2020-03-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0002_auto_20200316_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
