# Generated by Django 3.0.3 on 2020-02-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='accessible',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
