# Generated by Django 3.0.3 on 2020-02-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_auto_20200213_2325'),
        ('halls', '0003_auto_20200213_1535'),
    ]

    operations = [
    ]
