# Generated by Django 3.0.3 on 2020-02-04 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('halls', '0003_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('anonymous', models.BooleanField()),
                ('reported', models.BooleanField()),
                ('cleanliness', models.IntegerField()),
                ('social_life', models.IntegerField()),
                ('noise', models.IntegerField()),
                ('facilities', models.IntegerField()),
                ('roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls.RoomType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
