# Generated by Django 3.0.3 on 2020-02-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0004_merge_20200214_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reviewphotos',
            name='photo_path',
            field=models.ImageField(upload_to='review-uploads/'),
        ),
    ]
